[project]
name = "e2enf"
version = "0.2.0"
description = "End-to-End Neural Formant Synthesis"
authors = [
    { name = "Sumiharu Kobayashi", email = "t232525m@st.yamagata-u.ac.jp" },
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "h5py~=3.13.0",
    "hatchling~=1.27.0",
    "hydra-core~=1.3.2",
    "librosa~=0.11.0",
    "matplotlib~=3.10.3",
    "numpy~=2.2.6",
    "praat-parselmouth~=0.4.5",
    "pyreaper~=0.0.11",
    "pysptk~=1.0.1",
    "pyworld~=0.3.4",
    "scikit-learn~=1.6.1",
    "setuptools~=80.9.0",
    "tensorboard~=2.19.0",
    "torch==2.7.0+cu128; sys_platform == 'linux' and platform_machine == 'x86_64'",
    "torch==2.7.0; sys_platform == 'darwin' or (sys_platform == 'linux' and platform_machine == 'aarch64')",
    "torchaudio==2.7.0+cu128; sys_platform == 'linux' and platform_machine == 'x86_64'",
    "torchaudio==2.7.0; sys_platform == 'darwin' or (sys_platform == 'linux' and platform_machine == 'aarch64')",
    "tqdm~=4.67.1",
]

[dependency-groups]
dev = [
    "debugpy>=1.8.14",
    "jupyter-console>=6.6.3",
    "nbclassic>=1.3.1",
    "notebook>=7.4.3",
]

[project.scripts]
e2enf-anasyn = "e2enf.bin.anasyn:main"
e2enf-compute_statistics = "e2enf.bin.compute_statistics:main"
e2enf-data_augment = "e2enf.bin.data_augment:main"
e2enf-decode = "e2enf.bin.decode:main"
e2enf-extract_features = "e2enf.bin.extract_features:main"
e2enf-train = "e2enf.bin.train:main"
nf-train = "e2enf.bin.neuralformants.train:main"
nf-decode = "e2enf.bin.neuralformants.decode:main"

[tool.setuptools.packages.find]
where = ["src/"]
include = ["e2enf"]

[tool.uv]
index-strategy = "unsafe-best-match"

[tool.uv.sources]
torch = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux' and platform_machine == 'x86_64'" },
    { index = "pytorch-cpu", marker = "sys_platform == 'darwin' or (sys_platform == 'linux' and platform_machine == 'aarch64')" },
]
torchaudio = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux' and platform_machine == 'x86_64'" },
    { index = "pytorch-cpu", marker = "sys_platform == 'darwin' or (sys_platform == 'linux' and platform_machine == 'aarch64')" },
]
torchvision = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux' and platform_machine == 'x86_64'" },
    { index = "pytorch-cpu", marker = "sys_platform == 'darwin' or (sys_platform == 'linux' and platform_machine == 'aarch64')" },
]
pyworld = { git = "https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder.git" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.typos.default.extend-words]
fo = "fo"
