# @package _global_

defaults:
  - _self_
  - train/feature-mapping@train: invert-feature-mapping
  - feature-mapping@model: invert-feature-mapping
  - data: jvs.feature-mapping

hydra:
  run:
    dir: ./
  output_subdir: null
  job_logging:
    formatters:
      simple:
        format: "[%(asctime)s][%(levelname)s][%(module)s | %(lineno)s] %(message)s"
    disable_existing_loggers: false

out_dir: exp/jvs005_100.invert_fm # Directory to output training results.
seed: 12345 # Seed number for random numbers.
device: "cuda"
