# @package _global_

defaults:
  - _self_
  - generator: sifigan
  - discriminator: univnet
  - train/vocoder@train: sifigan
  - data: jvs005_100.sifigan


hydra:
  run:
    dir: ./
  output_subdir: null
  job_logging:
    formatters:
      simple:
        format: "[%(asctime)s][%(levelname)s][%(module)s | %(lineno)s] %(message)s"
    disable_existing_loggers: false

out_dir: exp/jvs005_100.sifigan # Directory to output training results.
seed: 12345 # Seed number for random numbers.
device: cuda
